### ISSUE TITLE
``https://charred-black.herokuapp.com/#/``  is broken.

### ISSUE THREAD

**Issue by CasperStaahl** [modality/charred-black#5]
``https://charred-black.herokuapp.com/#/`` seem to be broken. When is visit the website i can't interact with anything this is what it looks like.
![image](https://user-images.githubusercontent.com/72453813/126040303-1f222a25-75cb-4e8f-9c7d-fca2b6ee1f8d.png)

Console output looks like this:
```
Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at handleIframeLoad (burning.js:14)
    at HTMLIFrameElement.onload ((index):44)
burning-service.js:224 Loaded saved character names
burning-service.js:326 Loaded man starting stat points. 
burning-service.js:345 Loaded man resources. 
burning-service.js:326 Loaded dwarf starting stat points. 
burning-service.js:307 Loaded dwarf lifepaths. 1 settings
burning-service.js:326 Loaded elf starting stat points. 
burning-service.js:345 Loaded dwarf resources. 
burning-service.js:307 Loaded elf lifepaths. 2 settings
burning-service.js:326 Loaded orc starting stat points. 
burning-service.js:307 Loaded roden lifepaths. 3 settings
burning-service.js:345 Loaded roden resources. 
burning-service.js:307 Loaded orc lifepaths. 4 settings
burning-service.js:326 Loaded wolf starting stat points. 
burning-service.js:307 Loaded wolf lifepaths. 5 settings
burning-service.js:345 Loaded elf resources. 
burning-service.js:345 Loaded wolf resources. 
burning-service.js:345 Loaded orc resources. 
burning-service.js:345 Loaded troll resources. 
burning-service.js:307 Loaded troll lifepaths. 6 settings
burning-service.js:326 Loaded troll starting stat points. 
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
burning-service.js:364 Loaded skills. 
burning-service.js:311 Error: Getting man lifepaths from server failed: HTTP code 0: null
burning-service.js:330 Error: Getting roden stat points from server failed: HTTP code 0: null
angular.min.js:89 TypeError: Cannot read property '(Select Setting)' of undefined
    at calculateCurrentSettingLifepathNames (burning.js:2003)
    at a.BurningCtrl.$scope.onSettingChange (burning.js:385)
    at onLifepathsLoad (burning.js:1902)
    at c.onAllDatasetsLoaded (burning.js:407)
    at c.BurningDataService.datasetLoaded (burning-service.js:286)
    at burning-service.js:379
    at angular.min.js:71
    at F (angular.min.js:97)
    at F (angular.min.js:97)
    at F (angular.min.js:97)
(anonymous) @ angular.min.js:89
angular.min.js:89 TypeError: Cannot read property '(Select Setting)' of undefined
    at calculateCurrentSettingLifepathNames (https://charred-black.herokuapp.com/js/burning.js:2003:62)
    at a.BurningCtrl.$scope.onSettingChange (https://charred-black.herokuapp.com/js/burning.js:385:5)
    at onLifepathsLoad (https://charred-black.herokuapp.com/js/burning.js:1902:10)
    at https://charred-black.herokuapp.com/js/burning.js:407:5
    at c.BurningDataService.registerOnAllDatasetsLoaded (https://charred-black.herokuapp.com/js/burning-service.js:278:7)
    at c.BurningCtrl (https://charred-black.herokuapp.com/js/burning.js:406:15)
    at d (https://charred-black.herokuapp.com/js/angular.min.js:34:265)
    at Object.instantiate (https://charred-black.herokuapp.com/js/angular.min.js:34:394)
    at https://charred-black.herokuapp.com/js/angular.min.js:66:112
    at link (https://charred-black.herokuapp.com/js/angular-route.js:913:26) <div ng-view="" class="ng-scope">
(anonymous) @ angular.min.js:89
/#/:1 [DOM] Found 2 elements with non-unique id #cost: (More info: https://goo.gl/9p2vKq) <input class=​"form-control" id=​"cost" ng-model=​"currentGearCost" placeholder=​"Enter cost in rps" type=​"text">​ <input class=​"form-control" id=​"cost" ng-model=​"currentPropertyCost" placeholder=​"Enter cost in rps" type=​"text">​
/#/:1 [DOM] Found 4 elements with non-unique id #name: (More info: https://goo.gl/9p2vKq) <input class=​"form-control" id=​"name" ng-model=​"name" type=​"text">​ <input class=​"form-control" id=​"name" ng-model=​"currentGearDesc" placeholder=​"Enter name/​description" type=​"text">​ <input class=​"form-control" id=​"name" ng-model=​"currentPropertyDesc" placeholder=​"Enter name/​description" type=​"text">​ <input class=​"form-control" id=​"name" ng-model=​"currentRelationshipDesc" placeholder=​"Enter description" type=​"text">​
DevTools failed to load source map: Could not load content for https://charred-black.herokuapp.com/js/angular.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

This also happens on my phone.

**Comment by CasperStaahl** [comment]
This seems to be an issue on my part
